// Copyright 2026 RISC-V ECG Project
// SPDX-License-Identifier: Apache-2.0
// Auto-generated by scripts/quantize_resumamba.py

#ifndef RESUMAMBA_SCALES_H
#define RESUMAMBA_SCALES_H

#include <stdint.h>

typedef struct {
    const char *name;
    float scale;
    int32_t mult;
    int8_t shift;
} resumamba_tensor_scale_t;

#define RESUMAMBA_NUM_SCALES 85

static const resumamba_tensor_scale_t g_resumamba_scales[RESUMAMBA_NUM_SCALES] = {
    {"stem1_w", 200.091395f, 25612, 7},
    {"stem1_b", 106924.651807f, 106925, 0},
    {"stem2_w", 443.764506f, 28401, 6},
    {"stem2_b", 65641.124686f, 65641, 0},
    {"stem_out_dw_w", 140.266709f, 17954, 7},
    {"stem_out_pw_w", 110.550069f, 28301, 8},
    {"stem_out_b", 34977.712226f, 34978, 0},
    {"resu_0_entry_dw_w", 185.587864f, 23755, 7},
    {"resu_0_entry_pw_w", 49.064131f, 25121, 9},
    {"resu_0_entry_b", 16237.186225f, 32474, 1},
    {"resu_0_mid_dw_w", 191.111390f, 24462, 7},
    {"resu_0_mid_pw_w", 77.447475f, 19827, 8},
    {"resu_0_mid_b", 22018.416161f, 22018, 0},
    {"resu_0_out_dw_w", 179.228744f, 22941, 7},
    {"resu_0_out_pw_w", 56.300019f, 28826, 9},
    {"resu_0_out_b", 26890.075516f, 26890, 0},
    {"resu_0_enc_0_dw_w", 179.809530f, 23016, 7},
    {"resu_0_enc_0_pw_w", 55.134983f, 28229, 9},
    {"resu_0_enc_0_b", 25847.883275f, 25848, 0},
    {"resu_0_dec_0_dw_w", 177.384382f, 22705, 7},
    {"resu_0_dec_0_pw_w", 108.842311f, 27864, 8},
    {"resu_0_dec_0_b", 27403.486295f, 27403, 0},
    {"resu_0_enc_1_dw_w", 202.393996f, 25906, 7},
    {"resu_0_enc_1_pw_w", 102.748376f, 26304, 8},
    {"resu_0_enc_1_b", 18859.396516f, 18859, 0},
    {"resu_0_dec_1_dw_w", 183.496795f, 23488, 7},
    {"resu_0_dec_1_pw_w", 85.439018f, 21872, 8},
    {"resu_0_dec_1_b", 12811.418329f, 25623, 1},
    {"resu_0_enc_2_dw_w", 219.527586f, 28100, 7},
    {"resu_0_enc_2_pw_w", 79.468471f, 20344, 8},
    {"resu_0_enc_2_b", 15199.792341f, 30400, 1},
    {"resu_0_dec_2_dw_w", 192.781612f, 24676, 7},
    {"resu_0_dec_2_pw_w", 99.985717f, 25596, 8},
    {"resu_0_dec_2_b", 26143.781093f, 26144, 0},
    {"resu_1_entry_dw_w", 178.319521f, 22825, 7},
    {"resu_1_entry_pw_w", 85.684138f, 21935, 8},
    {"resu_1_entry_b", 20059.333633f, 20059, 0},
    {"resu_1_mid_dw_w", 169.670195f, 21718, 7},
    {"resu_1_mid_pw_w", 76.178921f, 19502, 8},
    {"resu_1_mid_b", 16658.950517f, 16659, 0},
    {"resu_1_out_dw_w", 181.309652f, 23208, 7},
    {"resu_1_out_pw_w", 37.542127f, 19222, 9},
    {"resu_1_out_b", 14744.662062f, 29489, 1},
    {"resu_1_enc_0_dw_w", 177.225950f, 22685, 7},
    {"resu_1_enc_0_pw_w", 64.053452f, 16398, 8},
    {"resu_1_enc_0_b", 23361.005753f, 23361, 0},
    {"resu_1_dec_0_dw_w", 174.058196f, 22279, 7},
    {"resu_1_dec_0_pw_w", 74.555250f, 19086, 8},
    {"resu_1_dec_0_b", 32828.664733f, 32829, 0},
    {"resu_1_enc_1_dw_w", 214.408229f, 27444, 7},
    {"resu_1_enc_1_pw_w", 77.463693f, 19831, 8},
    {"resu_1_enc_1_b", 14329.160283f, 28658, 1},
    {"resu_1_dec_1_dw_w", 147.279820f, 18852, 7},
    {"resu_1_dec_1_pw_w", 100.731809f, 25787, 8},
    {"resu_1_dec_1_b", 25724.858213f, 25725, 0},
    {"ssm_0_in_proj_w", 109.785477f, 28105, 8},
    {"ssm_0_dw_w", 44.113621f, 22586, 9},
    {"ssm_0_dw_b", 12129.468227f, 24259, 1},
    {"ssm_0_fwd_w", 169413.298006f, 169413, 0},
    {"ssm_0_bwd_w", 133816.942846f, 133817, 0},
    {"ssm_0_gate_proj_w", 104.490433f, 26750, 8},
    {"ssm_0_out_proj_w", 20.995557f, 21499, 10},
    {"ssm_0_out_b", 26727.752691f, 26728, 0},
    {"ssm_1_in_proj_w", 70.433684f, 18031, 8},
    {"ssm_1_dw_w", 105.247981f, 26943, 8},
    {"ssm_1_dw_b", 7708.645565f, 30835, 2},
    {"ssm_1_fwd_w", 276529.612012f, 276530, 0},
    {"ssm_1_bwd_w", 253235.076013f, 253235, 0},
    {"ssm_1_gate_proj_w", 122.016033f, 31236, 8},
    {"ssm_1_out_proj_w", 14.942578f, 30602, 11},
    {"ssm_1_out_b", 11883.648143f, 23767, 1},
    {"fuse_w", 265.372795f, 16984, 6},
    {"fuse_b", 19810.178728f, 19810, 0},
    {"cond_conv_0_w", 55.479432f, 28405, 9},
    {"adain_0_gamma_w", 106.080692f, 27157, 8},
    {"adain_0_gamma_b", 31034.187382f, 31034, 0},
    {"adain_0_beta_w", 129.628180f, 16592, 7},
    {"adain_0_beta_b", 29472.451978f, 29472, 0},
    {"cond_conv_1_w", 75.332869f, 19285, 8},
    {"adain_1_gamma_w", 98.234560f, 25148, 8},
    {"adain_1_gamma_b", 6113.388064f, 24454, 2},
    {"adain_1_beta_w", 126.594528f, 32408, 8},
    {"adain_1_beta_b", 23933.053709f, 23933, 0},
    {"head_w", 70.310176f, 17999, 8},
    {"head_b", 24354.029939f, 24354, 0},
};

#endif // RESUMAMBA_SCALES_H
